title: 'Presentation Hub'
default_lang: en
author:
  name: 'Site Author'
  email: siteauthor@email.com
taxonomies:
  - category
  - tag
  - author
  - filter
metadata:
  description: 'A short description of your Open Presentation Hub would go here'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
